import type { NextPage } from 'next'
import Head from 'next/head'
import CreateSchedulesButton from '../src/components/CreateSchedulesButton'
import TourCard from '../src/components/TourCard'
import { TourData } from '../src/type'

import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

  const testData: TourData[] = [
    {"title": "제목1", "content" : "내용1"},
    {"title": "제목2", "content" : "내용2"},
    {"title": "제목3", "content" : "내용3"},
  ]

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.card__wrapper}>
          <div className={styles.card__wrapperTitle}>여행 일정</div>
          {testData.map((tour,idx) => <TourCard key={idx} {...tour}></TourCard>)}
          <CreateSchedulesButton/>
        </div>
      </main>
    </div>
  )
}

export default Home
